# import = ["/home/tomppa/.config/alacritty/themes/themes/rose-pine.toml"]
# import = ["/home/tomppa/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["/home/tomppa/.config/alacritty/themes/themes/catppuccin.toml"]
# import = ["/home/tomppa/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
# import = ["/home/tomppa/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "tmux-256color"

[font]
size = 14

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
